#!/bin/sh
# Inherit vars
. ~/.shellprofile
export PATH="$HOME/.ashdwl/scripts:$PATH"

# ENV Vars
export QT_QPA_PLATFORM="wayland"
export QT_QPA_PLATFORMTHEME="qt6ct"

wal -R &

# Use wl-restart with --env flag for dwl
dwlblocks | dwl -s ~/.ashdwl/autostart.sh > /tmp/dwl.log 2>&1
