#!/bin/sh

# Inherit profile
. ~/.shellprofile

# Environment
export PATH="$HOME/.ashdwl/scripts:$PATH"
export XKB_DEFAULT_LAYOUT="us"
export XCURSOR_SIZE=24
export QT_QPA_PLATFORM="wayland"
export QT_QPA_PLATFORMTHEME="qt6ct"

# Run dwl
# Everything inside autostart.sh handles the pywal/xrdb timing
dwlblocks | dwl -s ~/.ashdwl/autostart.sh > /tmp/dwl.log 2>&1
